name: planner_app
description: A planner app to assist students with organization.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+11

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  auto_size_text: ^3.0.0
  crypto: ^3.0.2
  http: ^0.13.5
  collection: ^1.16.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  table_calendar: ^3.0.7
  clock: ^1.1.1
  flutter_local_notifications: ^13.0.0
  flutter_timezone: ^1.0.4
  timezone: ^0.9.1
  test: ^1.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  package_rename: ^1.0.0+1

flutter:
  uses-material-design: true
  assets:
    - icons/

flutter_app_name:
  name: "PlanAway"
